/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GGene_GN_Building_v0(4.1up)_instance_moved_instanced.glb --transform --format png --instanceall 
Files: GGene_GN_Building_v0(4.1up)_instance_moved_instanced.glb [78.83MB] > /Users/edge/Documents/Code/BlogPage_Production/static/test_scene/GGene_GN_Building_v0(4.1up)_instance_moved_instanced-transformed.glb [8.1MB] (90%)
*/

import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = React.createContext()

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/GGene_GN_Building_v0(4.1up)_instance_moved_instanced-transformed.glb')
  const instances = React.useMemo(
    () => ({
      FOG: nodes.FOG,
      TERRAIN: nodes.TERRAIN,
      Cube: nodes.Cube003,
      Cube1: nodes.Cube003_1,
      Cube2: nodes.Cube003_2,
      Cube3: nodes.Cube003_3,
      Cube4: nodes.Cube003_4,
      Cube5: nodes.Cube003_5,
      Cube6: nodes.Cube003_6,
      Cube7: nodes.Cube003_7,
      Cube8: nodes.Cube003_8,
      Cube9: nodes.Cube003_9,
      Cube10: nodes.Cube003_10,
      Cube11: nodes.Cube008,
      Cube12: nodes.Cube008_1,
      Cube13: nodes.Cube008_2,
      ProceduralBuilding: nodes.Procedural_Building009,
      ProceduralBuilding1: nodes.Procedural_Building013,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.FOG position={[0, 452.163, 0]} scale={[1170.727, 1005.122, 1302.391]} />
      <instances.TERRAIN scale={145662.531} />
      <group position={[-844.557, 0.002, 856.513]}>
        <instances.Cube />
        <instances.Cube1 />
        <instances.Cube2 />
        <instances.Cube3 />
        <instances.Cube4 />
        <instances.Cube5 />
        <instances.Cube6 />
        <instances.Cube7 />
        <instances.Cube8 />
        <instances.Cube9 />
        <instances.Cube10 />
      </group>
      <group position={[-844.794, 0, 832.115]}>
        <instances.Cube11 />
        <instances.Cube12 />
        <instances.Cube13 />
      </group>
      <instances.ProceduralBuilding position={[-844.482, 0, 880.001]} />
      <instances.ProceduralBuilding1 position={[-844.594, 0, 786.336]} />
    </group>
  )
}

useGLTF.preload('/GGene_GN_Building_v0(4.1up)_instance_moved_instanced-transformed.glb')
