/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ty_animated_1.gltf --transform 
Files: Ty_animated_1.gltf [5.98MB] > /Users/edge/Documents/Code/BlogPage/public/resources/models/Ty_animated_1-transformed.glb [232.11KB] (96%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Ty_animated_1-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <group name="005722">
          <group name="Hips" position={[-0.002, -0.223, 0.028]} rotation={[-2.663, -0.034, 0.008]}>
            <group name="LeftUpLeg" position={[0.069, 0.084, -0.038]} rotation={[2.653, 0.226, -3.056]}>
              <group name="LeftLeg" position={[0, 0.377, 0]} rotation={[2.982, 0.33, -3.041]}>
                <group name="LeftFoot" position={[0, 0.401, 0]} rotation={[-1.204, -0.078, 0.364]}>
                  <group name="LeftToe" position={[0, 0.134, 0]} rotation={[-1.946, -0.303, 0.207]} />
                </group>
              </group>
            </group>
            <group name="RightUpLeg" position={[-0.068, 0.083, -0.036]} rotation={[2.633, -0.487, 3.02]}>
              <group name="RightLeg" position={[0, 0.385, 0]} rotation={[2.983, -0.247, 3.051]}>
                <group name="RightFoot" position={[0, 0.401, 0]} rotation={[-1.261, 0.042, -0.488]}>
                  <group name="RightToe" position={[0, 0.135, 0]} rotation={[-1.89, 0.271, -0.197]} />
                </group>
              </group>
            </group>
            <group name="Spine" position={[-0.001, -0.084, 0.074]} rotation={[2.671, -0.034, -0.049]}>
              <group name="Spine1" position={[0, 0.135, 0]} rotation={[0.44, 0.012, 0.012]}>
                <group name="Spine2" position={[0, 0.059, 0]} rotation={[-0.697, -0.013, 0.035]}>
                  <group name="Neck" position={[0, 0.218, 0.011]} rotation={[0.916, -0.03, -0.071]}>
                    <group name="Head" position={[0, 0.083, 0]} rotation={[-0.667, -0.022, 0.062]} />
                  </group>
                  <group name="LeftShoulder" position={[0.08, 0.125, -0.003]} rotation={[0.157, 0.066, -1.254]}>
                    <group name="LeftArm" position={[0, 0.096, 0]} rotation={[-0.046, 0.001, -0.368]}>
                      <group name="LeftForeArm" position={[0, 0.261, 0]} rotation={[0.102, 0.105, 0.074]}>
                        <group name="LeftHand" position={[0, 0.249, 0]} rotation={[0.005, 0.005, 1.535]} />
                      </group>
                    </group>
                  </group>
                  <group name="RightShoulder" position={[-0.08, 0.126, -0.008]} rotation={[0.158, -0.065, 1.226]}>
                    <group name="RightArm" position={[0, 0.102, 0]} rotation={[-0.021, -0.013, 0.377]}>
                      <group name="RightForeArm" position={[0, 0.255, 0]} rotation={[0.064, -0.066, -0.077]}>
                        <group name="RightHand" position={[0, 0.255, 0]} rotation={[0.022, -0.021, -1.54]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <skinnedMesh name="Boy01_Hair_Geo" geometry={nodes.Boy01_Hair_Geo.geometry} material={materials.Boy01_Hair_MAT} skeleton={nodes.Boy01_Hair_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Hands_Geo" geometry={nodes.Boy01_Hands_Geo.geometry} material={materials.Boy01_Hands_MAT} skeleton={nodes.Boy01_Hands_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Head_Geo" geometry={nodes.Boy01_Head_Geo.geometry} material={materials.Boy01_Head_MAT} skeleton={nodes.Boy01_Head_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_LowerBody_Geo" geometry={nodes.Boy01_LowerBody_Geo.geometry} material={materials.Boy01_LowerBody_MAT} skeleton={nodes.Boy01_LowerBody_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Scarf_Geo" geometry={nodes.Boy01_Scarf_Geo.geometry} material={materials.Boy01_Scarf_MAT} skeleton={nodes.Boy01_Scarf_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Shoes_Geo" geometry={nodes.Boy01_Shoes_Geo.geometry} material={materials.Boy01_Shoes_MAT} skeleton={nodes.Boy01_Shoes_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_UpperBody_Geo" geometry={nodes.Boy01_UpperBody_Geo.geometry} material={materials.Boy01_UpperBody_MAT} skeleton={nodes.Boy01_UpperBody_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/Ty_animated_1-transformed.glb')
