/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Ty_animated_full_1.gltf --transform 
Files: Ty_animated_full_1.gltf [5.94MB] > /Users/edge/Documents/Code/BlogPage/public/resources/models/Ty_animated_full_1-transformed.glb [194.76KB] (97%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Ty_animated_full_1-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="Boy01_Hair_Geo" geometry={nodes.Boy01_Hair_Geo.geometry} material={materials.Boy01_Hair_MAT} skeleton={nodes.Boy01_Hair_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Hands_Geo" geometry={nodes.Boy01_Hands_Geo.geometry} material={materials.Boy01_Hands_MAT} skeleton={nodes.Boy01_Hands_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Head_Geo" geometry={nodes.Boy01_Head_Geo.geometry} material={materials.Boy01_Head_MAT} skeleton={nodes.Boy01_Head_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_LowerBody_Geo" geometry={nodes.Boy01_LowerBody_Geo.geometry} material={materials.Boy01_LowerBody_MAT} skeleton={nodes.Boy01_LowerBody_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Scarf_Geo" geometry={nodes.Boy01_Scarf_Geo.geometry} material={materials.Boy01_Scarf_MAT} skeleton={nodes.Boy01_Scarf_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_Shoes_Geo" geometry={nodes.Boy01_Shoes_Geo.geometry} material={materials.Boy01_Shoes_MAT} skeleton={nodes.Boy01_Shoes_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Boy01_UpperBody_Geo" geometry={nodes.Boy01_UpperBody_Geo.geometry} material={materials.Boy01_UpperBody_MAT} skeleton={nodes.Boy01_UpperBody_Geo.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/Ty_animated_full_1-transformed.glb')
